accounts/urls.py
from django.urls import path, include
from .views import login_view, logout_view, profile_update_view, profile_delete_view, accounts, error_view, organiser_list_view, confirm_view, verify_email_view, profile_view
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from solisite.settings import EMAIL_HOST_USER

from django.conf.urls.static import static
from django.conf import settings
app_name='accounts'
urlpatterns = [
    path('login/', login_view, name = 'login'),
    path('logout/', logout_view, name = 'logout'),
    path('organizer/', organiser_list_view, name='organiser_list'),
    path('profile/edit/', profile_update_view, name='profile_update'),
    path('profile/delete/', profile_delete_view, name='profile_delete'),
    path('profile/<str:organisation_name>/', profile_view, name='profile'),
    path('profile/<str:organisation_name>/events/', include('events.urls')),
    path('register/', accounts.as_view(), name='register'),
    path('error/', error_view, name='register_error'),
    path('confirm/', confirm_view, name="confirm"),
    path('verify/', verify_email_view, name="verify_email"),

    # password related stuff
    path('password_change/', auth_views.PasswordChangeView.as_view(
            template_name='register/password_change.html',
            success_url=reverse_lazy('accounts:password_change_complete')
        ), name="password_change"),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
            template_name='register/password_change_done.html'
        ), name='password_change_complete'),
    path('password_reset/', auth_views.PasswordResetView.as_view(
            template_name='register/request_password_reset.html',
            success_url=reverse_lazy('accounts:password_reset_done'),
            from_email=EMAIL_HOST_USER,
            email_template_name='register/password_reset_email.html',
            subject_template_name='register/password_reset_email_subject.txt'
        ), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
            template_name='register/request_password_reset_done.html'
        ), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
            template_name='register/password_reset.html',
            success_url=reverse_lazy('accounts:password_reset_complete')
        ), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
            template_name='register/password_reset_done.html'
        ), name='password_reset_complete'),
    #path(settings.MEDIA_URL, document_root = settings.MEDIA_URL),
]

events/urls.py
from django.urls import path, include
from .views import event_detail_view, event_create_view, event_update_view, event_delete_view

app_name = "events"
urlpatterns = [
	path('create/', event_create_view, name='event_create'),
	path('<int:id>/', event_detail_view, name='event_detail'),
	path('<int:id>/edit/', event_update_view, name='event_update'),
	path('<int:id>/delete/', event_delete_view, name='event_delete'),
	path('<int:id>/payment/', include('payment.urls')),
]

accounts/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from solisite.settings import HOST_URL_BASE

class UserAddress(models.Model):
    strasse = models.CharField(max_length=120)
    hnummer = models.CharField(max_length=120)
    plz = models.CharField(max_length=40)
    ort = models.CharField(max_length=120)
    country = models.CharField(max_length= 40, default = "Deutschland")

    class Meta:
        verbose_name='User Address'
        verbose_name_plural='User Address'

    def __str__(self):
        return self.strasse

    def getWholeAddress(self):
        return self.strasse + " " + self.hnummer + ", " + self.plz + " " + self.ort


class Organiser(User):
    TYPES = (
        ('gemeinnützig', 'gemeinnützig'),
        ('nicht gemeinnützig', 'nicht gemeinnützig'),
    )
    user_address = models.OneToOneField(
        UserAddress,
        on_delete=models.CASCADE,
        null = True,
        related_name = "user_adress_contact_set",
        related_query_name="organiser_address"
    )
    organisation_name = models.CharField(max_length=120)
    organisation_type = models.CharField(max_length=120, choices=TYPES)
    contact_first_name = models.CharField(max_length=120)
    contact_last_name = models.CharField(max_length=120)
    contact_phone = models.CharField(max_length=100, null=True, blank=True)
    iban = models.CharField(max_length=120, null=True, blank=True)
    bic = models.CharField(max_length=120, null=True, blank=True)
    bank_account_owner = models.CharField(max_length=120, null=True, blank=True)
    kontosite = models.URLField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    paypal_email = models.EmailField(null=True, blank=True, max_length=254)
    isActivated = models.BooleanField(default = True)
    confirmationCode = models.CharField(max_length = 60, default = 'nicht_migrierte_daten')
    acceptedTac = models.BooleanField() # The Organiser has accepted our terms and conditions

    picture = models.ImageField(null=True, blank=True, default = "default.png")

    def __str__(self):
        return self.organisation_name

    def get_share_url(self):
        return "{}{}".format(HOST_URL_BASE, reverse("accounts:profile", kwargs={"organisation_name": self.organisation_name})[1:])

    def get_confirm_url(self):
        return "{}{}?confirmationCode={}&id={}".format(HOST_URL_BASE, reverse("accounts:confirm")[1:], self.confirmationCode, self.id)

    def getContactPerson(self):
        return self.contact_first_name + " " + self.contact_last_name

    class Meta:
        verbose_name='Organiser'
        verbose_name_plural='Organiser'


class Customer(User):
    def __str__(self):
        return self.username

    class Meta:
        verbose_name='Customer'
        verbose_name_plural='Customers'


class Order(models.Model):
    article = models.ForeignKey('events.Buyable', on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, null=True, on_delete=models.CASCADE, related_name='customer_set')
    customer_mail = models.EmailField(max_length=120)
    amount = models.PositiveIntegerField(validators=[MinValueValidator(1)], default=0)
    price = models.DecimalField(max_digits=1000, decimal_places=2, validators=[MinValueValidator(0)])
    createdDateTime = models.DateTimeField(auto_now_add=True)
    changedDateTime = models.DateTimeField(auto_now=True)
    invoiceUID = models.CharField(max_length = 64, default = 'nicht_migrierte_orders')
    isPayed = models.BooleanField(default = False)
    acceptedTac = models.BooleanField()

    def setPrice(self):
        self.price = self.article.price * self.amount

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.views import View
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from .models import UserAddress, Organiser
from .forms import UserAddressForm, OrganiserForm, Register1, Register2, Register3
from django.core.mail import send_mail
from django.http import HttpResponse
from django.conf import settings
from solisite.settings import DEBUG
import string
import random
import math
from .filters import OrganiserFilter
from django.db.models.query import QuerySet
from urllib.parse import urlencode
from events.models import Event
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.core.files.storage import default_storage

from PIL import Image
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
import sys

def login_view(request):
    if request.user.is_authenticated:
        username = request.user
        return redirect('accounts:profile', Organiser.objects.get(username=username).organisation_name)
    else:
        if request.method == 'POST':

            username = request.POST.get('username')
            password = request.POST.get('password')
            try:
                organiser = Organiser.objects.get(email=username)
                print(organiser)
                username = organiser.username
            except:
                pass

            user = authenticate(request, username=username, password=password)

            if user is not None:
                o_organiser = Organiser.objects.get(username = user.username)
                if o_organiser is not None:
                    if o_organiser.isActivated == False:
                        buildAndSendEmail(o_organiser)
                        request.session['username'] = username
                        return redirect('accounts:verify_email')
                    else:
                        login(request, user)
                        return redirect('accounts:profile', Organiser.objects.get(username=username).organisation_name)
            else:
                messages.info(request, 'Username or Password is incorrect')
        context = {
			'authenticated': request.user.is_authenticated,
		}
        return render(request, 'accounts/login.html', context)


def logout_view(request):
    logout(request)
    return redirect('accounts:login')


def verify_email_view(request):
    assert(request.session.get('username')), "The username has to be in the session before this view is called!"
    organiser = get_object_or_404(Organiser, username=request.session.get('username'))
    if request.method == 'POST':
        buildAndSendEmail(organiser)
    context = {
        'organiser': organiser,
	}
    return render(request, 'register/check_your_emails.html', context)

def error_view(request):
    print("Error at registration")
    return render(request, 'register/error.html')


def organiser_list_view(request):
    try:
        entries_per_page = int(request.GET["epP"])
        page = int(request.GET["page"])
    except:
        entries_per_page = 10
        page = 1
    assert(page > 0), "Falscher URL Parameter!"
    assert(entries_per_page >= 1), "Falscher URL Parameter!"

    organisers = Organiser.objects.filter(is_active=True, isActivated = True)
    myFilter = OrganiserFilter(request.GET, queryset=organisers)
    organisers = myFilter.qs

    organisers_total = organisers.count()
    if organisers_total:
        pages = range(1, int(math.ceil(float(organisers_total) / float(entries_per_page))) + 1)
    else:
        pages = range(1, 2)
    lastPage = pages[-1]
    if page > lastPage:
        print("Automatically shifting to the last Page!")
        page = lastPage
    organisers = organisers.order_by('user_address__ort')[entries_per_page*(page - 1):entries_per_page*page]

    list_of_ids = []
    for organiser in organisers:
        list_of_ids.append(organiser.user_address.id)
    addresses = UserAddress.objects.filter(id__in=list_of_ids).distinct()
    cities = addresses.values('ort').order_by('ort')

    try:
        currentSearch = "?city=" + request.GET["city"] + "&"
    except:
        currentSearch = "?"

    context = {
        'organisers': organisers,
        'cities': cities,
        'myFilter': myFilter,
        'currentPage': page,
        'lastPage': lastPage,
        'entries_per_page': entries_per_page,
        'organisers_num': organisers_total,
        'pages': pages,
        'currentSearch': currentSearch,
    }
    return render(request, 'accounts/organiser_list.html', context)


def profile_view(request, organisation_name):
	organiser_object = get_object_or_404(Organiser, organisation_name = organisation_name)
	event_list = Event.objects.filter(creator = organiser_object)
	event_list = event_list.order_by('date')
	user = request.user
	logged_in = user.username == organiser_object.username
	context = {
		'organiser': organiser_object,
		'event_list': event_list,
	}

	if(logged_in):
		return render(request, "accounts/profile_organiser.html", context)
	else:
		return render(request, "accounts/profile_customer.html", context)


@login_required(login_url='accounts:login')
def profile_update_view(request):
	user = request.user
	organiser = Organiser.objects.get(username=user.username)
	address = organiser.user_address


	if request.method == 'POST':
		organiser_form = OrganiserForm(request.POST, instance = organiser)
		address_form = UserAddressForm(request.POST, instance = address)
		if organiser_form.is_valid() and address_form.is_valid():
			result = organiser_form.save(commit = False)

			if(request.FILES.get('picture')):
				picture = request.FILES.get('picture')
				picture.name =  user.username + picture.name

				pic = Image.open(picture)
				pic = pic.resize( (100,100) )
				output = BytesIO()
                
				pic.save(output, format='PNG', quality=100)
				output.seek(0)
				result.picture = InMemoryUploadedFile(output,'ImageField', "%s.jpg" %picture.name.split('.')[0], 'image/jpeg', sys.getsizeof(output), None)
			result.save()
			address.save()
			return redirect('accounts:profile', organisation_name=organiser.organisation_name)
	else:
		organiser_form = OrganiserForm(instance = organiser)
		address_form = UserAddressForm(instance = address)

	context = {
		'organiser_form': organiser_form,
		'address_form': address_form,
		'organiser_user': organiser,
	}
	return render(request, 'accounts/profile_update.html', context)


@login_required(login_url='accounts:login')
def profile_delete_view(request):
    user = request.user
    organiser = get_object_or_404(Organiser, username=user.username)
    if request.method == 'POST':
        logout(request)
        organiser.is_active = False
        organiser.save()
        return redirect('home')
    context = {
        'organiser_user': organiser,
    }
    return render(request, 'accounts/profile_delete.html', context)


class accounts(View):
    template_name = ['register/register_start.html',
                     'register/register_start2.html',
                     'register/register_start3.html',
					 'register/check_your_emails.html',
                     'register/register_finished.html']
    tags = ["email","pw","vname","nname","oname","art","strasse","username",
            "hnummer","plz","ort","telnr","kontoinhaber","iban","bic","kontourl", "description", "picture"]


    def get(self, request, *args, **kwargs):

        registerform = Register1()
        context = {
            'register1' : registerform,
        }
        return render(request, self.template_name[0], context)



    def post(self, request, *args, **kwargs):


        req = request.POST

        # Wir waren auf page 1:
        if "pw1" in req:
            form = Register1(request.POST)

            if form.is_valid() and form.cleaned_data['pw1'] == form.cleaned_data['pw2']:
                valid = True
                if Organiser.objects.filter(email = req.get('email')).exists():
                    valid = False
                    form.add_error('email', 'Diese Email wird bereits verwendet.')
                if Organiser.objects.filter(username = req.get('user')).exists():
                    valid = False
                    form.add_error('user', 'Der Username wird bereits verwendet.')
                if valid:
                    request.session["email"] = form.cleaned_data["email"]
                    request.session["pw"] = form.cleaned_data["pw1"]
                    request.session["username"] = form.cleaned_data["user"]
                    # "jump" to next page
                    form = Register2()
                    context = {
                        'register2' : form,
                    }
                    return render(request, self.template_name[1], context)

            if form.cleaned_data['pw1'] != form.cleaned_data['pw2']:
                form.add_error('pw1', 'Die Passwörter stimmen nicht überein')
            context = {
                'register1' : form,
            }
            return render(request, self.template_name[0], context)

        # Wir waren auf page 2:
        elif "nname" in req:

            form = Register2(request.POST)
            if form.is_valid():
                valid = True
                if Organiser.objects.filter(organisation_name = req.get('oname')).exists() or req.get('oname') == "edit" or req.get('oname') == "delete":
                    valid = False
                    form.add_error('oname', 'Diese Organisation ist bereits registriert.')
                if valid:
                    for tag in ["vname","nname","oname","art","strasse",
                         "hnummer","plz","ort","telnr", "description"]:

accounts/templates/accounts/login.html
{%  extends 'base.html' %}
{% block content %}

  <div>
    <div class="section cc-store-home-wrap">
      <div class="form-header">
        <div class="intro-content cc-homepage">
          <div class="intro-text">
            <div class="heading-jumbo">Willkommen!</div>
            <div class="div-block divider"></div>
            <div class="paragraph-bigger cc-bigger-white-light">Als Veranstalter einloggen<br></div>
          </div>
        </div>
      </div>
      <div class="container">
        <div class="w-form">
          {% for message in messages %}
            <p style="color:red;text-align:center;" id='messages'>{{message}}</p>
          {% endfor %}
          <form  method ="POST" class = "form" action = "."> {% csrf_token %}
            <div class="w-row">
              <div class="w-col w-col-3"></div>
              <div class="w-col w-col-6">
                <label for="username" class="field-label">Benutzername oder E-Mail</label>
                <input type="username" class="text-field-2 w-input" autofocus="true" maxlength="256" name="username" data-name="Name" required="" id="email">
                <label for="password">Passwort</label>
                <input type="password" class="text-field-2 w-input" maxlength="256" name="password" data-name="Email" id="passwort" required="">
                <div class="w-row">
                  <div class="w-col w-col-4"><input type="submit" value="Einloggen" data-wait="Please wait..." class="submit-button w-button"></div>
                  <div class="w-col w-col-8"><a href="{% url 'accounts:register' %}" class="link-2">Noch kein Konto? Hier registrieren!</a></div>
                </div>
                <div class="w-row">
                  <div class="w-col w-col-4"></div>
                  <div class="w-col w-col-8"><a href="{% url 'accounts:password_reset' %}">Passwort vergessen? Hier zurücksetzen</a></div>
                </div>
              </div>
              <div class="w-col w-col-3"></div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

accounts/templates/accounts/organiser_list.html
{% extends "base.html" %}

{% load custom_tags %}

{% block title %}
Liste aller Veranstalter
{% endblock %}

{% block content %}
<div class="section-19">
  <div class="w-container">
    <h3 class="heading-21">Hier finden Sie alle Veranstalter, die Sie bei uns unterstützen können!</h3>
    <div class="w-form">
      <form id="email-form" name="email-form" data-name="Email Form">
        <div class="w-row">
          <div class="w-col w-col-3"></div>
          <div class="w-col w-col-6">
            {{ myFilter.form.city|setHTMLAttributes:"{'class': 'text-field-2 w-input', 'placeholder': 'Nach Ort suchen...'}" }}
            <input type="submit" value="Suchen" class="submit-button-2 w-button">
            <a class="submit-button w-button" href="{% url 'accounts:organiser_list' %}">Alle anzeigen</a>
          </div>
          <div class="w-col w-col-3"></div>
        </div>
      </form>
    </div>
    <div class="pages-container">
      {% if currentPage > 1 %}
        <a href="{{currentSearch}}page={{currentPage|add:'-1'}}&epP={{entries_per_page}}" id="previous-page"></a>
      {% else %}
        <a class="disabled" id="previous-page"></a>
      {% endif %}
      <!-- Automatically collapse the Page indices to a smaller amount if a specified threshhold is reached. -->
      {% if lastPage < 10 %}
        {% for p in pages %}
          <a href="{{currentSearch}}page={{p}}&epP={{entries_per_page}}" class="page-index {% if currentPage == p %}current-page{% endif %}">{{ p }}</a>
        {% endfor %}
      {% else %}
        {% for p in pages %}
          {% if p|add:'4' < currentPage or p|add:'-4' > currentPage %}
          {% elif p|add:'4' == currentPage or p|add:'-4' == currentPage %}
            <a class="page-index">...</a>
          {% else %}
            <a href="{{currentSearch}}page={{p}}&epP={{entries_per_page}}" class="page-index {% if currentPage == p %}current-page{% endif %}">{{ p }}</a>
          {% endif %}
        {% endfor %}
      {% endif %}
      {% if currentPage < lastPage %}
        <a href="{{currentSearch}}page={{currentPage|add:'1'}}&epP={{entries_per_page}}" id="next-page"></a>
      {% else %}
        <a class="disabled" id="next-page"></a>
      {% endif %}
    </div>
    <div class="epP-container">
      <p class="epP-description">Einträge pro Seite:</p>
      <a class="epP-index {% if entries_per_page == 10 %}current-epP{% endif %}" href="{{currentSearch}}page={{currentPage}}&epP=10">10</a>
      <a class="epP-index {% if entries_per_page == 20 %}current-epP{% endif %}" href="{{currentSearch}}page={{currentPage}}&epP=20">20</a>
      <a class="epP-index {% if entries_per_page == 30 %}current-epP{% endif %}" href="{{currentSearch}}page={{currentPage}}&epP=30">30</a>
      <a class="epP-index {% if entries_per_page == 40 %}current-epP{% endif %}" href="{{currentSearch}}page={{currentPage}}&epP=40">40</a>
      <a class="epP-index {% if entries_per_page == 50 %}current-epP{% endif %}" href="{{currentSearch}}page={{currentPage}}&epP=50">50</a>
    </div>
    <div class="divider"></div>
  </div>
  {% for city in cities %}
    <div class="ort w-container">
      <h4 class="veranstaltungsort">{{ city.ort }}</h4>
      {% for organiser in organisers %}
        {% if organiser.user_address.ort == city.ort %}
          <div class="columns-8 w-row">
            <div class="normalize-image-col w-col w-col-2 w-col-small-2" style="padding-top: 8px; padding-bottom: 9px;">
              <a href="{% url 'accounts:profile' organiser.organisation_name %}">
                <img src="{{ organiser.picture.url }}" alt="" class="normalize-image">
              </a>
            </div>
            <div class="w-col w-col-10 w-col-small-10">
              <a href="{% url 'accounts:profile' organiser.organisation_name %}" class="veranstalter">{{ organiser.organisation_name }}</a>
              <p class="organizer-description"><span>{% if organiser.description %}{{ organiser.description|shorten_to:"390" }}{% else %}Dieser Veranstalter hat keine Beschreibung{% endif %}</span></p>
            </div>
          </div>
        {% endif %}
      {% endfor %}
      <div class="platz"></div>
      <div class="divider"></div>
    </div>
  {% endfor %}
  {% if not organisers_num %}
    <div class="ort w-container">
      <div class="platz"></div>
      <div class="divider"></div>
    </div>
  {% endif %}
  <div class="w-container">
    <div class="pages-container">
      {% if currentPage > 1 %}
        <a href="{{currentSearch}}page={{currentPage|add:'-1'}}&epP={{entries_per_page}}" id="previous-page"></a>
      {% else %}
        <a class="disabled" id="previous-page"></a>
      {% endif %}
      <!-- Automatically collapse the page indices to a smaller amount if a specified threshhold is reached. -->
      {% if lastPage < 10 %}
        {% for p in pages %}
          <a href="{{currentSearch}}page={{p}}&epP={{entries_per_page}}" class="page-index {% if currentPage == p %}current-page{% endif %}">{{ p }}</a>
        {% endfor %}
      {% else %}
        {% for p in pages %}
          {% if p|add:'4' < currentPage or p|add:'-4' > currentPage %}
          {% elif p|add:'4' == currentPage or p|add:'-4' == currentPage %}
            <a class="page-index">...</a>
          {% else %}
            <a href="{{currentSearch}}page={{p}}&epP={{entries_per_page}}" class="page-index {% if currentPage == p %}current-page{% endif %}">{{ p }}</a>
          {% endif %}
        {% endfor %}
      {% endif %}
      {% if currentPage < lastPage %}
        <a href="{{currentSearch}}page={{currentPage|add:'1'}}&epP={{entries_per_page}}" id="next-page"></a>
      {% else %}
        <a class="disabled" id="next-page"></a>
      {% endif %}
    </div>
    <p class="paragraph-29">Haben Sie Ihren Lieblings-Kulturbetrieb nicht gefunden?<br>Dann erzählen Sie ihm doch von dieser Seite!</p>
  </div>
</div>
<script>
  window.onload = function () {
    var descs = document.getElementsByClassName("organizer-description");
    var max_tries = 300;
    for(var i = 0; i < descs.length; i++) {
      if(descs[i].clientHeight < descs[i].scrollHeight) {
        var content = descs[i].firstChild;
        var j = 0;
        while(content.offsetHeight > 80 && j < max_tries) {
          j++;
          content.innerHTML = content.innerHTML.slice(0, -1);
        }
        content.innerHTML = content.innerHTML.slice(0, -3);
        content.innerHTML = content.innerHTML + "...";
      }
    }
  }
</script>
{% endblock %}

accounts/templates/accounts/profile_organiser.html
{% extends "base.html" %}

{% load static %}

{% block title %}
Events von {{ organiser }}
{% endblock %}

{% block additionaljs %}
<script src="{% static 'js/custom.js' %}" type="text/javascript"></script>
{% endblock %}

{% block content %}
<div class="section cc-store-home-wrap">
    <div class="container-16 w-container">
      <div class="intro-text">
	  	<img src="{{ organiser.picture.url }}" alt="Profilbild" class="normalize-image image-12">
        <h1 class="heading-2">{{ organiser.organisation_name }}</h1>
        <div class="div-block"></div>
      </div>
      {% if organiser.description %}
	  	<p class="paragraph-18">{{ organiser.description|linebreaksbr }}</p>
	  {% endif %}
      <h3>Alle Events von {{ organiser.organisation_name }}</h3>
      <div class="w-layout-grid grid-6">
        {% for event in event_list %}
          <div class="text-block-2">{{ event.date }}</div>
          <div class="text-block-3"><a href='{{event.get_absolute_url}}'>{{ event.name }}</a></div>
          <a href="{{event.get_absolute_url}}edit/"><img src="{% static 'images/icons8-edit-24.png' %}" alt=""></a>
          <a href="{{event.get_absolute_url}}delete/"><img src="{% static 'images/delete-24px.svg' %}" alt=""></a>
        {% endfor %}
	  </div>
    </div>
    <div class="container-14 w-container">
		{% if organiser.paypal_email %}
			<a href="{% url 'accounts:events:event_create' organiser_user.organisation_name %}" class="button-5 w-button">Neue Veranstaltung erstellen</a>
		{% else %}
			<p style="color: red;">Sie können erst neue Veranstaltungen erstellen, wenn Sie eine E-Mail-Adresse für Ihr Paypal-Konto in Ihrem Profil hinterlegt haben, da Sie sonst keine Zahlungen empfangen können.</p>
			<a class="button-9 w-button" href="{% url 'accounts:profile_update' %}">Paypal E-Mail-Adresse hinzufügen</a>
		{% endif %}
	</div>
	{% include 'copy_link_field.html' with link=organiser.get_share_url %}
  </div>
  <div class="divider"></div>
  <div class="section-21">
	<div class="w-container">
	  <h3>Ihre Daten</h3>
	  <div class="w-row">
		<div class="column-25 w-col w-col-6">
		  <p class="paragraph-15">Ansprechpartner</p>
		  <p>{{ organiser.contact_first_name }} {{ organiser.contact_last_name }}</p>
		</div>
		<div class="column-26 w-col w-col-6">
		  <p class="paragraph-15">E-Mail-Adresse</p>
		  <p class="paragraph-16">{{ organiser.email }}</p>
		</div>
	  </div>
	  <div class="w-row">
		<div class="column-27 w-col w-col-6">
		  <p class="paragraph-15">Name der Organisation</p>
		  <p>{{ organiser.organisation_name }}</p>
		</div>
		<div class="column-28 w-col w-col-6">
		  <p class="paragraph-15">Art der organisation</p>
		  <p>{{ organiser.organisation_type }}</p>
		</div>
	  </div>
	  <div class="w-row">
		<div class="column-29 w-col w-col-6">
		  <p class="paragraph-15">Adresse</p>
		  <p>{{ organiser.user_address.strasse }} {{ organiser.user_address.hnummer }}<br>{{ organiser.user_address.plz }}, {{ organiser.user_address.ort }}</p>
		</div>
		<div class="column-30 w-col w-col-6">
			{% if organiser.contact_phone %}
			  <p class="paragraph-15">Telefonnummer</p>
			  <p>{{ organiser.contact_phone }}</p>
			{% endif %}
		</div>
	  </div>
	  <div class="w-row">
        <div class="column-29 w-col w-col-6">
		  {% if organiser.paypal_email %}
          	<p class="paragraph-15">Ihr Paypal-Geschäftskonto</p>
		  	<p>{{ organiser.paypal_email }}</p>
		  {% endif %}
        </div>
        <div class="column-30 w-col w-col-6"></div>
      </div>
	  <a href="{% url 'accounts:profile_update' %}" class="button-9 w-button">Profil bearbeiten</a>
	</div>
  </div>
  <div class="container-17 w-container"><a href="{% url 'accounts:profile_delete' %}" class="button-11 w-button red-background">Profil löschen</a></div>
{% endblock %}