accounts/urls.py
from django.urls import path, include
from .views import login_view, logout_view, profile_update_view, profile_delete_view, accounts, error_view, organiser_list_view, confirm_view, verify_email_view, profile_view
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from solisite.settings import EMAIL_HOST_USER

from django.conf.urls.static import static
from django.conf import settings
app_name='accounts'
urlpatterns = [
    path('login/', login_view, name = 'login'),
    path('logout/', logout_view, name = 'logout'),
    path('organizer/', organiser_list_view, name='organiser_list'),
    path('profile/edit/', profile_update_view, name='profile_update'),
    path('profile/delete/', profile_delete_view, name='profile_delete'),
    path('profile/<str:organisation_name>/', profile_view, name='profile'),
    path('profile/<str:organisation_name>/events/', include('events.urls')),
    path('register/', accounts.as_view(), name='register'),
    path('error/', error_view, name='register_error'),
    path('confirm/', confirm_view, name="confirm"),
    path('verify/', verify_email_view, name="verify_email"),

    # password related stuff
    path('password_change/', auth_views.PasswordChangeView.as_view(
            template_name='register/password_change.html',
            success_url=reverse_lazy('accounts:password_change_complete')
        ), name="password_change"),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
            template_name='register/password_change_done.html'
        ), name='password_change_complete'),
    path('password_reset/', auth_views.PasswordResetView.as_view(
            template_name='register/request_password_reset.html',
            success_url=reverse_lazy('accounts:password_reset_done'),
            from_email=EMAIL_HOST_USER,
            email_template_name='register/password_reset_email.html',
            subject_template_name='register/password_reset_email_subject.txt'
        ), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
            template_name='register/request_password_reset_done.html'
        ), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
            template_name='register/password_reset.html',
            success_url=reverse_lazy('accounts:password_reset_complete')
        ), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
            template_name='register/password_reset_done.html'
        ), name='password_reset_complete'),
    #path(settings.MEDIA_URL, document_root = settings.MEDIA_URL),
]

events/urls.py
from django.urls import path, include
from .views import event_detail_view, event_create_view, event_update_view, event_delete_view

app_name = "events"
urlpatterns = [
	path('create/', event_create_view, name='event_create'),
	path('<int:id>/', event_detail_view, name='event_detail'),
	path('<int:id>/edit/', event_update_view, name='event_update'),
	path('<int:id>/delete/', event_delete_view, name='event_delete'),
	path('<int:id>/payment/', include('payment.urls')),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<!--  This site was created in Webflow. http://www.webflow.com  -->
<!--  Last Published: Sat Mar 21 2020 10:47:23 GMT+0000 (Coordinated Universal Time)  -->
<html data-wf-page="5e75d1ef0014e6c922138c6a" data-wf-site="5e74a11331a7130e3cb649b9">
<head>
  <meta charset="utf-8">
  <title>{% block title %}Soli-Ticket - Jetzt Unterstützen oder Organisation anmelden{% endblock %}</title>
  <link rel="manifest" href="">
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="{% static 'images/ms-icon-144x144.png">
  <meta name="theme-color" content="#ffffff">
  <meta property="og:url" content="https://www.soli-ticket.de">
  <meta property="og:type" content="website">
  <meta property="og:title" content="Soli-Ticket - Jetzt Unterstützen oder Organisation anmelden">
  <meta property="og:description" content="Wir helfen Unternehmen, Vereinen, Künstlern und Kulturstätten den finanziellen Schaden, der durch die Corona-Epidemie entsteht, einzudämmen.">
  <meta property="og:image" content="{% static 'images/ms-icon-310x310.png' %}">
  <meta content="width=device-width, initial-scale=1" name="viewport">
  <meta content="Webflow" name="generator">

  <!-- IMAGES -->
  <link href="{% static 'images/favico.ico' %}" rel="shortcut icon" type="image/x-icon">
  <link href="{% static 'images/webclip.ico' %}" rel="apple-touch-icon">
  <link rel="apple-touch-icon" sizes="57x57" href="{% static 'images/apple-icon-57x57.png' %}">
  <link rel="apple-touch-icon" sizes="60x60" href="{% static 'images/apple-icon-60x60.png' %}">
  <link rel="apple-touch-icon" sizes="72x72" href="{% static 'images/apple-icon-72x72.png' %}">
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'images/apple-icon-76x76.png' %}">
  <link rel="apple-touch-icon" sizes="114x114" href="{% static 'images/apple-icon-114x114.png' %}">
  <link rel="apple-touch-icon" sizes="120x120" href="{% static 'images/apple-icon-120x120.png' %}">
  <link rel="apple-touch-icon" sizes="144x144" href="{% static 'images/apple-icon-144x144.png' %}">
  <link rel="apple-touch-icon" sizes="152x152" href="{% static 'images/apple-icon-152x152.png' %}">
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/apple-icon-180x180.png' %}">
  <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'images/android-icon-192x192.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="96x96" href="{% static 'images/favicon-96x96.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon-16x16.png' %}">

  <!-- CSS -->
  <link href="{% static 'css/custom.css' %}?v={{ site_version }}" rel="stylesheet" type="text/css">
  <link href="{% static 'css/normalize.css' %}?v={{ site_version }}" rel="stylesheet" type="text/css">
  <link href="{% static 'css/webflow.css' %}?v={{ site_version }}" rel="stylesheet" type="text/css">
  <link href="{% static 'css/soliticket.webflow.css' %}?v={{ site_version }}" rel="stylesheet" type="text/css">
  {% block additionalcss %}{% endblock %}

  <!-- JAVASCRIPT -->
  <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js" type="text/javascript"></script>
  <script type="text/javascript">WebFont.load({  google: {    families: ["Montserrat:100,100italic,200,200italic,300,300italic,400,400italic,500,500italic,600,600italic,700,700italic,800,800italic,900,900italic"]  }});</script>
  <!-- [if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js" type="text/javascript"></script><![endif] -->
  <script type="text/javascript">!function(o,c){var n=c.documentElement,t=" w-mod-";n.className+=t+"js",("ontouchstart"in o||o.DocumentTouch&&c instanceof DocumentTouch)&&(n.className+=t+"touch")}(window,document);</script>
  <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.4.1.min.220afd743d.js?site=5e74a11331a7130e3cb649b9" type="text/javascript" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
	<script src="{% static 'js/webflow.js' %}" type="text/javascript"></script>
	<!-- [if lte IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif] -->
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-80752466-7"></script>
  <link href="{% static 'datepicker/datepicker.css' %}" rel="stylesheet" type="text/css">
  <script src="{% static 'datepicker/datepicker.js' %}" type="text/javascript"></script>
  <script src="{% static 'datepicker/datepicker.de-DE.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/custom.js' %}" type="text/javascript"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'UA-80752466-7');
  </script>
  {% block additionaljs %}{% endblock additionaljs %}
</head>
<body>
  <div id="navbar-space-reserver">    
    <div class="navbar position-fixed">
      <div data-collapse="medium" data-animation="default" data-duration="400" class="navigation w-nav">
          <div class="navigation-wrap">
              <div class="logo-title-wrapper">
                  <div class="logo">
                    <a href="https://www.soli-ticket.de" class="w-inline-block">
                      <img src="{% static 'images/soli-ticket-logo.png' %}" width="" alt="" class=""></div>
                    </a>
                  <div class="title">
                      <h1 class="heading"><a href="https://www.soli-ticket.de" class="link-block w-inline-block"><strong class="bold-text">Soli-Ticket</strong></a></h1>
                  </div>
              </div>
              <div class="menu">
                <nav role="navigation" class="navigation-items w-nav-menu">
                  <a href="{% url 'home' %}" class="w-nav-link">Home</a>
                  {% if organiser_user %}
                  <a href="{% url 'accounts:profile' organiser_user.organisation_name %}" class="w-nav-link">Mein Profil</a>
                  {% endif %}
                  <a href="{% url 'blog' %}" class="w-nav-link">News</a>
                  <a href="{% url 'about' %}" class="w-nav-link">Über Uns</a>
                  <a href="{% url 'faq' %}" class="w-nav-link">FAQ</a>
                  {% if organiser_user %}
                  <a href="{% url 'accounts:logout' %}" class="w-nav-link">Abmelden</a>
                  {% else %}
                  <a href="{% url 'accounts:login' %}" class="w-nav-link">Anmelden</a>
                  {% endif %}
                </nav>
                <div class="menu-button w-nav-button"><img src="{% static 'images/menu-icon_1menu-icon.png' %}" width="22" alt="" class="menu-icon"></div>
              </div>
          </div>
      </div>
      <div class="headerline"></div>
    </div>
  </div>
  {% block content %}

  {% endblock %}
  <div class="section">
    <div class="container">
      <div class="footer-wrap">
        <div class="w-row">
          <div class="w-col w-col-4 w-col-small-4 w-col-tiny-4">
            <a href="https://www.facebook.com/soliticket.de/" target="_blank" class="w-inline-block">
              <img src="{% static 'images/icons8-facebook-26.png' %}" alt="">
            </a>
          </div>
          <div class="w-col w-col-4 w-col-small-4 w-col-tiny-4">
            <a href="https://www.instagram.com/soli_ticket.de/" target="_blank" class="w-inline-block">
              <img src="{% static 'images/icons8-instagram-26.png' %}" alt="">
            </a>
          </div>
          <div class="w-col w-col-4 w-col-small-4 w-col-tiny-4">
            <a href="http://linkedin.com/company/soli-ticket" target="_blank" class="w-inline-block">
              <img src="{% static 'images/icons8-linkedin-26.png' %}" alt="">
            </a>
          </div>
        </div>
      </div>
      <div class="footer-wrap">
        <a href="{% url 'contact' %}" class="link">Kontakt</a>
        <a href="{% url 'imprint' %}" class="link">Impressum</a>
        <a href="{% url 'agb' %}" class="link">AGB</a>
        <a href="{% url 'privacy_policy' %}" class="link">Datenschutz</a>
      </div>
    </div>
  </div>
  <div id="additionals">
    <button id="to-top-button" class="submit-button w-button"></button>
    {% include 'cookie_banner.html' %}
  </div>
  <div id="cookie-banner-placeholder"></div>
  </body>
</html>

templates/cookie_banner.html
<div class="cookie-banner" id="cookie-banner" style="display: none;">
    <p style="margin: auto;">Diese Seite verwendet Cookies, um Ihnen unseren Service bestmöglich anbieten zu können. Mit der Nutzung dieser Seite stimmen Sie der Verwendung von Cookies zu.</p>
    <div class="buttons">
        <a href="{% url 'privacy_policy' %}" class="more-info w-button submit-button">Weitere Informationen</a>
        <button class="close-banner w-button submit-button">Verstanden</button>
    </div>
</div>

templates/copy_link_field.html
<div class="w-container">
    <h6 class="heading-20">Teilen Sie diesen Link, um auch andere zum Unterstützen aufzurufen</h6>
    <div class="copy-link-container">
        <input class="text-field-2 w-input" id="link" value="{{ link }}" readonly onclick="copyLink();">
        <div id="copy-button" onclick="copyLink();" title="In Zwischenablage kopieren"></div>
    </div>
</div>

templates/email_footer.html
<tr>
    <td valign="top" id="templateFooter"><table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnFollowBlock" style="min-width:100%;">
<tbody class="mcnFollowBlockOuter">
<tr>
<td align="center" valign="top" style="padding:9px" class="mcnFollowBlockInner">
<table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnFollowContentContainer" style="min-width:100%;">
<tbody><tr>
<td align="center" style="padding-left:9px;padding-right:9px;">
<table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;" class="mcnFollowContent">
<tbody><tr>
<td align="center" valign="top" style="padding-top:9px; padding-right:9px; padding-left:9px;">
<table align="center" border="0" cellpadding="0" cellspacing="0">
<tbody><tr>
    <td align="center" valign="top">
        <!--[if mso]>
        <table align="center" border="0" cellspacing="0" cellpadding="0">
        <tr>
        <![endif]-->
        
            <!--[if mso]>
            <td align="center" valign="top">
            <![endif]-->
            
            
                <table align="left" border="0" cellpadding="0" cellspacing="0" style="display:inline;">
                    <tbody><tr>
                        <td valign="top" style="padding-right:10px; padding-bottom:9px;" class="mcnFollowContentItemContainer">
                            <table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnFollowContentItem">
                                <tbody><tr>
                                    <td align="left" valign="middle" style="padding-top:5px; padding-right:10px; padding-bottom:5px; padding-left:9px;">
                                        <table align="left" border="0" cellpadding="0" cellspacing="0" width="">
                                            <tbody><tr>
                                                
                                                    <td align="center" valign="middle" width="24" class="mcnFollowIconContent">
                                                        <a href="https://www.facebook.com/soliticket.de/" target="_blank"><img src="https://cdn-images.mailchimp.com/icons/social-block-v2/color-facebook-48.png" alt="Facebook" style="display:block;" height="24" width="24" class=""></a>
                                                    </td>
                                                
                                                
                                            </tr>
                                        </tbody></table>
                                    </td>
                                </tr>
                            </tbody></table>
                        </td>
                    </tr>
                </tbody></table>
            
            <!--[if mso]>
            </td>
            <![endif]-->
        
            <!--[if mso]>
            <td align="center" valign="top">
            <![endif]-->
            
            
                <table align="left" border="0" cellpadding="0" cellspacing="0" style="display:inline;">
                    <tbody><tr>
                        <td valign="top" style="padding-right:10px; padding-bottom:9px;" class="mcnFollowContentItemContainer">
                            <table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnFollowContentItem">
                                <tbody><tr>
                                    <td align="left" valign="middle" style="padding-top:5px; padding-right:10px; padding-bottom:5px; padding-left:9px;">
                                        <table align="left" border="0" cellpadding="0" cellspacing="0" width="">
                                            <tbody><tr>
                                                
                                                    <td align="center" valign="middle" width="24" class="mcnFollowIconContent">
                                                        <a href="https://www.soli-ticket.de" target="_blank"><img src="https://cdn-images.mailchimp.com/icons/social-block-v2/color-link-48.png" alt="Website" style="display:block;" height="24" width="24" class=""></a>
                                                    </td>
                                                
                                                
                                            </tr>
                                        </tbody></table>
                                    </td>
                                </tr>
                            </tbody></table>
                        </td>
                    </tr>
                </tbody></table>
            
            <!--[if mso]>
            </td>
            <![endif]-->
        
            <!--[if mso]>
            <td align="center" valign="top">
            <![endif]-->
            
            
                <table align="left" border="0" cellpadding="0" cellspacing="0" style="display:inline;">
                    <tbody><tr>
                        <td valign="top" style="padding-right:0; padding-bottom:9px;" class="mcnFollowContentItemContainer">
                            <table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnFollowContentItem">
                                <tbody><tr>
                                    <td align="left" valign="middle" style="padding-top:5px; padding-right:10px; padding-bottom:5px; padding-left:9px;">
                                        <table align="left" border="0" cellpadding="0" cellspacing="0" width="">
                                            <tbody><tr>
                                                
                                                    <td align="center" valign="middle" width="24" class="mcnFollowIconContent">
                                                        <a href="https://www.instagram.com/soli_ticket.de/" target="_blank"><img src="https://cdn-images.mailchimp.com/icons/social-block-v2/color-instagram-48.png" alt="Instagram" style="display:block;" height="24" width="24" class=""></a>
                                                    </td>
                                                
                                                
                                            </tr>
                                        </tbody></table>
                                    </td>
                                </tr>
                            </tbody></table>
                        </td>
                    </tr>
                </tbody></table>
            
            <!--[if mso]>
            </td>
            <![endif]-->
        
        <!--[if mso]>
        </tr>
        </table>
        <![endif]-->
    </td>
</tr>
</tbody></table>
</td>
</tr>
</tbody></table>
</td>
</tr>
</tbody></table>

</td>
</tr>
</tbody>
</table><table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnDividerBlock" style="min-width:100%;">
<tbody class="mcnDividerBlockOuter">
<tr>
<td class="mcnDividerBlockInner" style="min-width: 100%; padding: 10px 18px 25px;">
<table class="mcnDividerContent" border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width: 100%;border-top: 2px solid #EEEEEE;">
<tbody><tr>
<td>
<span></span>
</td>
</tr>
</tbody></table>
<!--            
<td class="mcnDividerBlockInner" style="padding: 18px;">
<hr class="mcnDividerContent" style="border-bottom-color:none; border-left-color:none; border-right-color:none; border-bottom-width:0; border-left-width:0; border-right-width:0; margin-top:0; margin-right:0; margin-bottom:0; margin-left:0;" />
-->
</td>
</tr>
</tbody>
</table><table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnTextBlock" style="min-width:100%;">
<tbody class="mcnTextBlockOuter">
<tr>
<td valign="top" class="mcnTextBlockInner" style="padding-top:9px;">
<!--[if mso]>
<table align="left" border="0" cellspacing="0" cellpadding="0" width="100%" style="width:100%;">
<tr>
<![endif]-->

<!--[if mso]>
<td valign="top" width="600" style="width:600px;">
<![endif]-->
<table align="left" border="0" cellpadding="0" cellspacing="0" style="max-width:100%; min-width:100%;" width="100%" class="mcnTextContentContainer">
<tbody><tr>

<td valign="top" class="mcnTextContent" style="padding-top:0; padding-right:18px; padding-bottom:9px; padding-left:18px;">
<br>
<strong>Unsere E-Mail-Adresse:</strong><br>
<a href="mailto:soliticket@gmail.com">soliticket@gmail.com</a><br>
<br>
Yannis Beuke, Ivan Khomutovskiy, Nils König, Jannis Berndt, Christoph Kirchherr, Fabian Mahling GbR<br>
Zum Jagenstein 8<br>
14478 Potsdam<br>
</td>
</tr>
</tbody></table>
<!--[if mso]>
</td>
<![endif]-->

<!--[if mso]>
</tr>
</table>
<![endif]-->
</td>
</tr>
</tbody>
</table></td>
</tr>