accounts/urls.py
from django.urls import path, include
from .views import login_view, logout_view, profile_update_view, profile_delete_view, accounts, error_view, organiser_list_view, confirm_view, verify_email_view, profile_view
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from solisite.settings import EMAIL_HOST_USER

from django.conf.urls.static import static
from django.conf import settings
app_name='accounts'
urlpatterns = [
    path('login/', login_view, name = 'login'),
    path('logout/', logout_view, name = 'logout'),
    path('organizer/', organiser_list_view, name='organiser_list'),
    path('profile/edit/', profile_update_view, name='profile_update'),
    path('profile/delete/', profile_delete_view, name='profile_delete'),
    path('profile/<str:organisation_name>/', profile_view, name='profile'),
    path('profile/<str:organisation_name>/events/', include('events.urls')),
    path('register/', accounts.as_view(), name='register'),
    path('error/', error_view, name='register_error'),
    path('confirm/', confirm_view, name="confirm"),
    path('verify/', verify_email_view, name="verify_email"),

    # password related stuff
    path('password_change/', auth_views.PasswordChangeView.as_view(
            template_name='register/password_change.html',
            success_url=reverse_lazy('accounts:password_change_complete')
        ), name="password_change"),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
            template_name='register/password_change_done.html'
        ), name='password_change_complete'),
    path('password_reset/', auth_views.PasswordResetView.as_view(
            template_name='register/request_password_reset.html',
            success_url=reverse_lazy('accounts:password_reset_done'),
            from_email=EMAIL_HOST_USER,
            email_template_name='register/password_reset_email.html',
            subject_template_name='register/password_reset_email_subject.txt'
        ), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
            template_name='register/request_password_reset_done.html'
        ), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
            template_name='register/password_reset.html',
            success_url=reverse_lazy('accounts:password_reset_complete')
        ), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
            template_name='register/password_reset_done.html'
        ), name='password_reset_complete'),
    #path(settings.MEDIA_URL, document_root = settings.MEDIA_URL),
]

events/urls.py
from django.urls import path, include
from .views import event_detail_view, event_create_view, event_update_view, event_delete_view

app_name = "events"
urlpatterns = [
	path('create/', event_create_view, name='event_create'),
	path('<int:id>/', event_detail_view, name='event_detail'),
	path('<int:id>/edit/', event_update_view, name='event_update'),
	path('<int:id>/delete/', event_delete_view, name='event_delete'),
	path('<int:id>/payment/', include('payment.urls')),
]

events/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MinValueValidator
from accounts.models import Organiser
from decimal import Decimal
from solisite.settings import HOST_URL_BASE

class Eventlocation(models.Model):
	creator = models.ForeignKey(Organiser, on_delete=models.CASCADE, 
								related_name = "address_contact_set",
								related_query_name="event_location")
	createdDateTime = models.DateTimeField(auto_now_add=True)
	changedDateTime = models.DateTimeField(auto_now=True)
	location_name = models.CharField(max_length=120)
	country = models.CharField(max_length=120, null=True, blank=True, default="Deutschland")
	city = models.CharField(max_length=120, null=True, blank=True)
	street = models.CharField(max_length=120, null=True, blank=True)
	house_number = models.CharField(max_length=120, null=True, blank=True)
	post_code = models.CharField(max_length=40, null=True, blank=True)

	def __str__(self):
		return self.location_name

class Event(models.Model):
	creator = models.ForeignKey(Organiser, on_delete=models.CASCADE, 
								related_name = "event_contact_set",
								related_query_name="event")
	createdDateTime = models.DateTimeField(auto_now_add=True)
	changedDateTime = models.DateTimeField(auto_now=True)
	name = models.CharField(max_length=120)
	description = models.TextField()
	date = models.DateField()
	time = models.TimeField(null=True, blank=True)
	location = models.ForeignKey(Eventlocation, on_delete=models.SET_NULL, null=True, related_name='+')

	def get_absolute_url(self):
		return reverse("accounts:events:event_detail", kwargs={'organisation_name': self.creator.organisation_name, "id": self.id})

	def get_share_url(self):
		return "{}{}".format(HOST_URL_BASE, reverse("accounts:events:event_detail", kwargs={'organisation_name': self.creator.organisation_name, "id": self.id})[1:])

	def __str__(self):
		return self.name

class Buyable(models.Model):
	SEVEN = round(Decimal(0.07), 2)
	NINETEEN = round(Decimal(0.19), 2)
	ZERO = round(Decimal(0.00), 2)
	TAX_RATES = [(NINETEEN, '19%'), (SEVEN, '7%'), (ZERO, '0%')]
	creator = models.ForeignKey(Organiser, on_delete=models.CASCADE, 
								related_name = "buyable_contact_set",
								related_query_name="buyable")
	createdDateTime = models.DateTimeField(auto_now_add=True)
	changedDateTime = models.DateTimeField(auto_now=True)
	buyable_name = models.CharField(max_length=120)
	price = models.DecimalField(max_digits=1000, decimal_places=2, validators=[MinValueValidator(0)])
	belonging_event = models.ForeignKey(Event, on_delete=models.CASCADE,
										related_name='event_buyable',
										related_query_name='buyables_set')
	tax_rate = models.DecimalField(decimal_places = 2, max_digits = 3, choices=TAX_RATES, default = ZERO)

	def __str__(self):
		return self.buyable_name

events/forms.py
from django import forms
from django.forms import formset_factory, inlineformset_factory, modelformset_factory

from .models import Event, Eventlocation, Buyable

class EventlocationForm(forms.ModelForm):
	class Meta:
		model = Eventlocation
		fields = [
			'location_name',
			'city',
			'street',
			'house_number',
			'post_code',
		]

	def clean_city(self):
		data = self.cleaned_data["city"]
		if data is not None:
			data = data.capitalize()
		return data

class BuyableForm(forms.ModelForm):
	class Meta:
		model = Buyable
		fields = [
			'buyable_name',
			'price',
			'tax_rate',
		]
		
BuyableFormSet = formset_factory(BuyableForm, extra=5, max_num=5)
BuyableInlineFormSet = inlineformset_factory(Event, Buyable, form=BuyableForm, extra=5, max_num = 5)
BuyableModelFormSet = modelformset_factory(Buyable, form=BuyableForm, extra=5, max_num = 5)

def validate_with_initial(formset):
	valid = True
	for form in formset:
		if form.has_changed():
			if not form.is_valid():
				valid = False
				print('INVALID')
	return valid

class EventForm(forms.ModelForm):
	class Meta:
		model = Event
		fields = [
			'name',
			'description',
			'date',
		]

events/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.forms import inlineformset_factory, modelformset_factory
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.urls import reverse, reverse_lazy
from django.conf import settings
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from decimal import Decimal
from .models import Event, Eventlocation, Buyable
from .forms import EventForm, EventlocationForm, BuyableForm, BuyableFormSet, BuyableInlineFormSet, BuyableModelFormSet, validate_with_initial
from accounts.models import Organiser, Customer, Order
from accounts.forms import OrderForm, OrderContactForm, BaseOrderFormset
import uuid
import random
import string
import pdb

def event_detail_view(request, id, organisation_name):
	event = get_object_or_404(Event, id=id)
	organisation = event.creator
	buyables = Buyable.objects.filter(belonging_event=event)
	OrderFormSet = inlineformset_factory(Customer, Order, form=OrderForm, formset=BaseOrderFormset, fields=['amount',], extra=buyables.count(), can_delete=False)

	if request.method == 'POST':
		order_formset = OrderFormSet(request.POST)
		contact_form = OrderContactForm(request.POST)
		if not organisation.paypal_email:
			return render(request, 'event/error.html')

		if order_formset.is_valid() and contact_form.is_valid():
			sum = 0
			o_uid = invoiceUID_generator()
	
			for order_form in order_formset.orders_to_be_saved():
				order = order_form.save(commit=False)
				order.article = buyables[int(order_form.prefix[-1])]
				order.price = buyables[int(order_form.prefix[-1])].price * order.amount
				order.customer_mail = contact_form.cleaned_data["email"]
				order.acceptedTac = contact_form.cleaned_data["acceptedTac"]
				order.invoiceUID = o_uid
				order.save()
				sum += order.price

			if organisation.paypal_email:
				request.session["invoiceUID"] = o_uid
				request.session["sum"] = float(sum)
				request.session["paypal_email"] = organisation.paypal_email
				return redirect(reverse('accounts:events:payment:process', kwargs={'organisation_name': organisation.organisation_name, 'id': id}))
	else:
		order_formset = OrderFormSet()
		contact_form = OrderContactForm()

	withoutMwst = True
	for buyable in buyables:
		if buyable.tax_rate != 0.00:
			withoutMwst = False

	context = {
		'event': event,
		'buyables': buyables,
		'order_formset': order_formset,
		'formset': zip(buyables, order_formset),
		'organiser': organisation,
		'contact_form': contact_form,
		'withoutMwst': withoutMwst,
	}
	return render(request, "event/event_detail.html", context)


@login_required(login_url='accounts:login')
def event_create_view(request, organisation_name):
	user = request.user
	organiser = get_object_or_404(Organiser, username=user.username)
	if request.method == 'POST':
		event_form = EventForm(request.POST)
		location_form = EventlocationForm(request.POST)
		buyable_formset = BuyableModelFormSet(request.POST, queryset=Buyable.objects.none())
		if event_form.is_valid() and location_form.is_valid() and validate_with_initial(buyable_formset):
			event = event_form.save(commit=False)
			location = location_form.save(commit=False)
			location.creator = organiser
			location.save()
			event.location = location
			event.creator = organiser
			event.save()
			for buyable_form in buyable_formset:
				if buyable_form.has_changed():
					buyable = buyable_form.save(commit=False)
					buyable.creator = organiser
					buyable.belonging_event = event
					buyable.save()
			if Event.objects.filter(creator = organiser).count() == 1:
				send_email_firstEvent(organiser)
			try:
				organiser.acceptedTac = True if request.POST.get("checkbox") != "" else False
				organiser.save()
			except:
				pass
			return redirect('accounts:profile', organisation_name=organisation_name)
	else:
		event_form = EventForm()
		location_form = EventlocationForm()
		buyable_formset = BuyableModelFormSet(queryset=Buyable.objects.none())

	context = {
		'event_form': event_form,
		'location_form': location_form,
		'buyable_formset': buyable_formset,
		'organiser_user': organiser,
	}
	return render(request, "event/event_create.html", context)

@login_required(login_url='accounts:login')
def event_update_view(request, id, organisation_name):
	user = request.user
	organiser = get_object_or_404(Organiser, username=user.username)
	event = get_object_or_404(Event, id=id)
	location = event.location
	if request.method == 'POST':
		event_form = EventForm(request.POST, instance = event)
		location_form = EventlocationForm(request.POST, instance = location)
		buyable_formset = BuyableInlineFormSet(request.POST, instance = event)
		if event_form.is_valid() and location_form.is_valid() and buyable_formset.is_valid():
			location.save()
			event.save()
			buyables = buyable_formset.save(commit=False)
			print(buyables)
			for buyable in buyables:
				buyable.creator = organiser
				buyable.save()
			for obj in buyable_formset.deleted_objects:
				obj.delete()

			return redirect('accounts:profile', organisation_name=organiser.organisation_name)
	else:
		event_form = EventForm(instance = event)
		location_form = EventlocationForm(instance = location)
		buyable_formset = BuyableInlineFormSet(instance=event)

	context = {
		'event_form': event_form,
		'location_form': location_form,
		'buyable_formset': buyable_formset,
		'organiser_user': organiser,
	}
	return render(request, "event/event_update.html", context)

def event_delete_view(request, id, organisation_name):
	event = get_object_or_404(Event, id=id)
	user = request.user
	organiser = get_object_or_404(Organiser, username=user.username)
	if request.method == "POST":
		event.delete()
		return redirect('accounts:profile', organiser.organisation_name)
	context = {
		"event": event,
		'organiser_user': organiser,
	}
	return render(request, "event/event_delete.html", context)


def profile_redirect_view(request, organiser):
	return redirect('accounts:profile', organiser)

def event_detail_redirect_view(request, id):
	event = get_object_or_404(Event, id=id)
	return redirect('accounts:events:event_detail', id=id, organiser=event.creator.organisation_name)


def invoiceUID_generator(size = 7, chars= string.digits):
	uid = 'ST'+''.join(random.choice(chars) for _ in range(size))
	existingUIDs = Order.objects.filter(invoiceUID = uid).values('invoiceUID')

	# Sollten schon Orders dazu existieren, wird solange eine neue UID erzeugt und die Daten geholt, bis des Queryset o_orders leer ist.
	while existingUIDs:
		uid = 'ST'+''.join(random.choice(chars) for _ in range(size))
		existingUIDs = Order.objects.filter(invoiceUID = uid).values('invoiceUID')
	return uid


def send_email_firstEvent(organiser):
	subject = 'Glückwunsch! Sie haben Ihre erste Veranstaltung erstellt'
	html_message = render_to_string('email/first_event_created.html')
	plain_message = strip_tags(html_message)
	if settings.DEBUG:
		to = ['roessler.paul@web.de', 'kolzmertz@gmail.com', organiser.email]
	else:
		to = [organiser.email]
	send_mail(subject, plain_message, settings.EMAIL_HOST_USER, to, html_message = html_message)

events/templates/event/error.html
{%  extends 'base.html' %}

{% block content %}

<div class="section-28">
    <div class="w-container">
      <h1>ups...</h1>
      <p>Hallo lieber Unterstützer! Wir haben vor kurzer Zeit ein Update veröffentlicht, bei dem der Veranstalter eine PayPal Email-Adresse hinterlegen muss, um weiterhin Unterstützungen erhalten zu können. Dies wird in Kürze geschehen. Wir arbeiten mit Hochdruck daran. <br>Um von Neuerungen zu erfaheren, können Sie sich gerne auf der News-Seite für den Newsletter anmelden.<br></p><a href="#">News</a></div>
  </div>
{% endblock %}

events/templates/event/event_create.html
{% extends 'base.html' %}

{% load static %}

{% load custom_tags %}

{% block title %}
Neue Veranstaltung erstellen
{% endblock %}

{% block content %}
    <div class="section cc-store-home-wrap">
        <div class="form-header">
            <div class="intro-content cc-homepage">
                <div class="intro-text">
                    <div class="heading-jumbo">Erzählen Sie uns etwas über Ihre Veranstaltung</div>
                    <div class="div-block"></div>
                    <div class="paragraph-bigger cc-bigger-white-light">Veranstaltung erstellen<br></div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="w-form">
                <form id="wf-form-Veranstaltung-neu" name="wf-form-Veranstaltung-neu" data-name="Email Form" class="form" method="POST"> {% csrf_token %}
                    <div class="w-row">
                        <div class="w-col w-col-3 w-col-tiny-tiny-stack"></div>
                        <div class="w-col w-col-6 w-col-tiny-tiny-stack">
							<label for="{{ event_form.name.id_for_label }}">Name der Veranstaltung</label>
							{{ event_form.name.errors }}
							{{ event_form.name|setHTMLAttributes:"{'class':'text-field-2 w-input', 'placeholder':'Veranstaltungsname'}" }}
							<label for="{{ location_form.location_name.id_for_label }}">Wo Hätte die Veranstaltung stattgefunden?</label>
							{{ location_form.location_name.errors }}
							{{ location_form.location_name|setHTMLAttributes:"{'class':'text-field-2 w-input', 'placeholder':'Name des Veranstaltungsortes'}" }}
                            <div class="w-row">
                                <div class="w-col w-col-9">
									{{ location_form.street.errors }}
									{{ location_form.street|setHTMLAttributes:"{'class':'text-field-2 w-input', 'placeholder':'Straße (optional)'}" }}
                                </div>
                                <div class="w-col w-col-3">
									{{ location_form.house_number.errors }}
									{{ location_form.house_number|setHTMLAttributes:"{'class':'text-field-2 w-input', 'placeholder':'HausNr (optional)'}" }}
                                </div>
                            </div>
                            <div class="w-row">
                                <div class="w-col w-col-4">
									{{ location_form.post_code.errors }}
									{{ location_form.post_code|setHTMLAttributes:"{'class':'text-field-2 w-input', 'placeholder':'Postleitzahl (optional)'}" }}
                                </div>
                                <div class="w-col w-col-8">
									{{ location_form.city.errors }}
									{{ location_form.city|setHTMLAttributes:"{'class':'text-field-2 w-input', 'placeholder':'Ort (optional)'}" }}
                                </div>
							</div>
							<label for="{{ event_form.date.id_for_label }}">Wann Hätte die Veranstaltung stattgefunden?</label>
							{{ event_form.date.errors }}
							{{ event_form.date|setHTMLAttributes:"{'class':'text-field-2 w-input', 'autocomplete': 'off', 'placeholder':'Format: DD.MM.YYYY'}" }}
                            <script>
                                $(function () {
                                  $("#id_date").datepicker({
                                      language:"de-DE",
                                      format:"dd.mm.yyyy",
                                      autoHide: true,
                                      weekStart: 1,
                                  });
                                });
                            </script>
                            <!-- <input type="text" class="text-field-2 w-input" maxlength="256" name="DateTime" data-name="DateTime" placeholder="" id="DateTime" required=""> -->
                            <label for="{{ event_form.description.id_for_label }}" class="field-label-3">Kurzbeschreibung / Aufruf an ihre Unterstützer</label>
			  				<label for="{{ event_form.description.id_for_label }}" class="field-label-2">Ergänzen Sie hier neben mehr Informationen zu Ihrer Veranstaltung gerne auch eine persönliche Botschaft an Ihre Unterstützer</label>
							{{ event_form.description.errors }}
							{{ event_form.description|setHTMLAttributes:"{'class':'textarea text-field-2 w-input', 'placeholder':'Erzählen Sie mehr!'}" }}
                            <label for="Name-der-Organisation-2" class="field-label-5">Fügen Sie nun die verschiedenen Dinge hinzu, die Ihre Besucher/Kunden üblicherweise vor und während Ihrer Veranstaltungen erworben hätten. Dazu gehören natürlich die Tickets, aber auch z.B. die Portion Popcorn, die Cola oder anderes</label>
                            <div class="w-layout-grid grid-7">
                                <label>Tickets/Getränke/...</label>
                                <label>Preis (€)</label>
                                <label>Mwst</label>
                                {{ buyable_formset.management_form }}
                                {% for buyable_form in buyable_formset %}
                                    <div>
                                        {{ buyable_form.buyable_name.errors }}
                                        {{ buyable_form.buyable_name|setHTMLAttributes:"{'class':'text-field-2 w-input', 'placeholder':'Bezeichnung des Tickets/Getränks/der Speise'}" }}
                                    </div>
                                    <div>
                                        {{ buyable_form.price.errors }}
                                        {{ buyable_form.price|setHTMLAttributes:"{'class': 'text-field-2 w-input', 'placeholder': '0,00', 'min': '0'}" }}
                                    </div>
                                    <div>
                                        {{ buyable_form.tax_rate.errors }}
                                        {{ buyable_form.tax_rate|setHTMLAttributes:"{'class': 'text-field-2 w-select'}" }}
                                    </div>
                                {% endfor %}
                            </div>
                            {% if not organiser_user.acceptedTac %}
                            <label class="w-checkbox">
                                <input type="checkbox" id="checkbox" name="checkbox" data-name="Checkbox" class="w-checkbox-input" required>
                                <span class="w-form-label">Ich habe die AGB des Plattformbetreibers zur Kenntnis genommen und bin mit deren Geltung einverstanden<br>
                                  <a href="{% url 'agb' %}">Link zu den AGB</a>
                                </span>
                            </label>
                            {% endif %}
							<div class="w-row">
								<div class="w-col w-col-3"><input type="submit" value="Fertig!" data-wait="Bitte warten..." class="submit-button w-button"></div>
								<div class="w-col w-col-9"><a href="{% url 'accounts:profile' organiser_user.organisation_name %}" class="button-4 w-button">Abbrechen</a></div>
							</div>
						</div>
                        <div class="w-col w-col-3 w-col-tiny-tiny-stack"></div>
                    </div>
                </form>
                <div class="w-form-done">
                    <div>Thank you! Your submission has been received!</div>
                </div>
                <div class="w-form-fail">
                    <div>Oops! Ihre Angaben sind fehlerhaft. Versuchen Sie es erneut.</div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

events/templates/event/event_delete.html
{% extends "base.html" %}

{% load static %}

{% block title %}
{{event.name}} Löschen?
{% endblock %}

{% block content %}
		<div class="section-9">
		  <div class="w-row">
			<div class="w-col w-col-3"></div>
			<div class="w-col w-col-6">
			<form action='.' method='POST'> {% csrf_token %}
			  <h3>Möchten Sie das Event "{{event.name}}" wirklich löschen?</h3>
			  <div class="container-3 w-container"><input type='submit' class="button-3 w-button red-background" value='Ja, Löschen!'/></div>
			  <p></p>
			  <div class="container-4 w-container"><a href="{% url 'accounts:profile' organiser_user.organisation_name %}" class="button-4 w-button">Abbrechen</a></div>
			</form>
			</div>
			<div class="w-col w-col-3"></div>
		  </div>
		</div>
{% endblock %}

events/templates/event/profile_organiser.html
{% extends "base.html" %}

{% load static %}

{% block title %}
Events von {{ organiser }}
{% endblock %}

{% block additionaljs %}
<script src="{% static 'js/custom.js' %}" type="text/javascript"></script>
{% endblock %}

{% block content %}

<div class="section cc-store-home-wrap">
    <div class="container-16 w-container">
      <div class="intro-text">
        <h1 class="heading-2">{{ organiser.organisation_name }}</h1>
        <div class="div-block"></div>
      </div>
      {% if organiser.description %}
	  	<p class="paragraph-18">{{ organiser.description|linebreaksbr }}</p>
	  {% endif %}
      <h3>Alle Events von {{ organiser.organisation_name }}</h3>
      <div class="w-layout-grid grid-6">
        {% for event in event_list %}
          <div class="text-block-2">{{ event.date }}</div>
          <div class="text-block-3"><a href='{{event.get_absolute_url}}'>{{ event.name }}</a></div>
          <a href="{{event.get_absolute_url}}edit/"><img src="{% static 'images/icons8-edit-24.png' %}" alt=""></a>
          <a href="{{event.get_absolute_url}}delete/"><img src="{% static 'images/delete-24px.svg' %}" alt=""></a>
        {% endfor %}
	  </div>
    </div>
    <div class="container-14 w-container">
		{% if organiser.paypal_email %}
			<a href="{% url 'events:event_create' %}" class="button-5 w-button">Neue Veranstaltung erstellen</a>
		{% else %}
			<p>Sie können erst neue Veranstaltungen erstellen, wenn Sie eine Email-Adresse für Ihr Paypal-Konto in Ihrem Profil hinterlegt haben, da Sie sonst keine Zahlungen empfangen können.</p>
		{% endif %}
	</div>
    <div class="w-container">
      <h6 class="heading-20">Teilen Sie diesen Link mit ihren Unterstützern, um sie zum Spenden aufzurufen</h6>
      <div class="w-form">
        <div class="w-layout-grid grid-4">
          <div></div>
  		  <input type="text" class="text-field-2 w-input" maxlength="256" name="field" data-name="Field" readonly id="link" value="{{ organiser.get_share_url }}">
  		  <img src="{% static 'images/icons8-copy-24.png' %}" alt="" onclick="copyLink();" id="copyToClip" title="In Zwischenablage kopieren">
  		</div>
      </div>
    </div>
  </div>
  <div class="divider"></div>
  <div class="section-21">
	<div class="w-container">
	  <h3>Ihre Daten</h3>
	  <div class="w-row">
		<div class="column-25 w-col w-col-6">
		  <p class="paragraph-15">Ansprechpartner</p>
		  <p>{{ organiser.contact_first_name }} {{ organiser.contact_last_name }}</p>
		</div>
		<div class="column-26 w-col w-col-6">
		  <p class="paragraph-15">Email-Adresse</p>
		  <p class="paragraph-16">{{ organiser.email }}</p>
		</div>
	  </div>
	  <div class="w-row">
		<div class="column-27 w-col w-col-6">
		  <p class="paragraph-15">Name der Organisation</p>
		  <p>{{ organiser.organisation_name }}</p>
		</div>
		<div class="column-28 w-col w-col-6">
		  <p class="paragraph-15">Art der organisation</p>
		  <p>{{ organiser.organisation_type }}</p>
		</div>
	  </div>
	  <div class="w-row">
		<div class="column-29 w-col w-col-6">
		  <p class="paragraph-15">Adresse</p>
		  <p>{{ organiser.user_address.strasse }} {{ organiser.user_address.hnummer }}<br>{{ organiser.user_address.plz }}, {{ organiser.user_address.ort }}</p>
		</div>
		<div class="column-30 w-col w-col-6">
			{% if organiser.contact_phone %}
			  <p class="paragraph-15">Telefonnummer</p>
			  <p>{{ organiser.contact_phone }}</p>
			{% endif %}
		</div>
	  </div>
	  <div class="w-row">
        <div class="column-29 w-col w-col-6">
		  {% if organiser.paypal_email %}
          	<p class="paragraph-15">Ihr Paypal-Geschäftskonto</p>
		  	<p>{{ organiser.paypal_email }}</p>
		  {% endif %}
        </div>
        <div class="column-30 w-col w-col-6"></div>
      </div>
	  <a href="{% url 'accounts:profile_update' %}" class="button-9 w-button">Profil bearbeiten</a>
	</div>
  </div>
  <div class="container-17 w-container"><a href="{% url 'accounts:profile_delete' %}" class="button-11 w-button red-background">Profil löschen</a></div>
{% endblock %}